logs:
    - name: root
      level: info
      formatter: "%d%T%m%n"
      appenders:
          - type: FileLogAppender
            file: root.txt
          - type: StdoutLogAppender
    - name: system
      level: info
      formatter: "%d%T%m%n"
      appenders:
          - type: FileLogAppender
            file: system.txt
          - type: StdoutLogAppender

system:
  port: 9900
  value: 15
  int_vec: 
    - 10
    - 30
  int_list: [30,40,50]
  int_set: [60,70,80,60]
  int_uset: [30,20,60,20]
  str_int_map: 
        k: 30
        k2: 20
        k3: 10  
  str_int_umap: 
        k: 40
        k2: 40
        k3: 20 
